'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Localization
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PlatformStudio.Localization", GetType(Localization).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Script Error.
        '''</summary>
        Friend Shared ReadOnly Property actionProc_() As String
            Get
                Return ResourceManager.GetString("actionProc_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Could not initialize some control variables. These controls will not be accessible in your script..
        '''</summary>
        Friend Shared ReadOnly Property actionProc_CouldNotInitVarsError() As String
            Get
                Return ResourceManager.GetString("actionProc_CouldNotInitVarsError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to processing a script.
        '''</summary>
        Friend Shared ReadOnly Property actionProc_Description() As String
            Get
                Return ResourceManager.GetString("actionProc_Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The script in trigger, {0}, could not be executed because it contains an error..
        '''</summary>
        Friend Shared ReadOnly Property actionProc_Error() As String
            Get
                Return ResourceManager.GetString("actionProc_Error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error message:.
        '''</summary>
        Friend Shared ReadOnly Property actionProc_ErrorMessage() As String
            Get
                Return ResourceManager.GetString("actionProc_ErrorMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Script Error.
        '''</summary>
        Friend Shared ReadOnly Property actionProc_ErrorType() As String
            Get
                Return ResourceManager.GetString("actionProc_ErrorType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &quot;Game&quot; object doesn&apos;t exist or is incorrectly defined.\nPlease make sure this line exists in your global code:.
        '''</summary>
        Friend Shared ReadOnly Property actionProc_GameObjectDoesntExistError() As String
            Get
                Return ResourceManager.GetString("actionProc_GameObjectDoesntExistError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading the script.
        '''</summary>
        Friend Shared ReadOnly Property actionProc_LoadScriptDesc() As String
            Get
                Return ResourceManager.GetString("actionProc_LoadScriptDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All Files (*.*)|*.*|Image Files (*.bmp, *.gif, *.jpg, *.png)|*.bmp;*.gif;*.jpg;*.png|Text Files (*.txt, *.doc, *.rtf)|*.txt;*.doc;*.rtf|HTML Files (*.htm, *.html)|*.htm;*.html|Sound Files (*.wav)|*.wav|Music Files (*.mid, *.mp3)|*.mid;*.mp3|Help Files (*.hlp; *.chm)|*.hlp;*.chm.
        '''</summary>
        Friend Shared ReadOnly Property allFileFilter() As String
            Get
                Return ResourceManager.GetString("allFileFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Anonymous.
        '''</summary>
        Friend Shared ReadOnly Property anonymous() As String
            Get
                Return ResourceManager.GetString("anonymous", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Cancel.
        '''</summary>
        Friend Shared ReadOnly Property cancelButton() As String
            Get
                Return ResourceManager.GetString("cancelButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Health.
        '''</summary>
        Friend Shared ReadOnly Property counters_Health() As String
            Get
                Return ResourceManager.GetString("counters_Health", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lives.
        '''</summary>
        Friend Shared ReadOnly Property counters_Lives() As String
            Get
                Return ResourceManager.GetString("counters_Lives", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Score.
        '''</summary>
        Friend Shared ReadOnly Property counters_Score() As String
            Get
                Return ResourceManager.GetString("counters_Score", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Button{0}.
        '''</summary>
        Friend Shared ReadOnly Property defaultButtonText() As String
            Get
                Return ResourceManager.GetString("defaultButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MyCompany, Inc..
        '''</summary>
        Friend Shared ReadOnly Property defaultCompany() As String
            Get
                Return ResourceManager.GetString("defaultCompany", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Control{0}.
        '''</summary>
        Friend Shared ReadOnly Property defaultControlName() As String
            Get
                Return ResourceManager.GetString("defaultControlName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Created by MyName\n\nPowered by JumpCraft.
        '''</summary>
        Friend Shared ReadOnly Property defaultCredits() As String
            Get
                Return ResourceManager.GetString("defaultCredits", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MyGame.
        '''</summary>
        Friend Shared ReadOnly Property defaultGameName() As String
            Get
                Return ResourceManager.GetString("defaultGameName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MyGame Version 1.0.
        '''</summary>
        Friend Shared ReadOnly Property defaultGameWithVersion() As String
            Get
                Return ResourceManager.GetString("defaultGameWithVersion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Type your help text here..
        '''</summary>
        Friend Shared ReadOnly Property defaultHelpText() As String
            Get
                Return ResourceManager.GetString("defaultHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Label{0}.
        '''</summary>
        Friend Shared ReadOnly Property defaultLabelText() As String
            Get
                Return ResourceManager.GetString("defaultLabelText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Level {0}.
        '''</summary>
        Friend Shared ReadOnly Property defaultLevelName() As String
            Get
                Return ResourceManager.GetString("defaultLevelName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to support@mywebsite.com.
        '''</summary>
        Friend Shared ReadOnly Property defaultSupportEmail() As String
            Get
                Return ResourceManager.GetString("defaultSupportEmail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Timer {0}.
        '''</summary>
        Friend Shared ReadOnly Property defaultTimerName() As String
            Get
                Return ResourceManager.GetString("defaultTimerName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (default).
        '''</summary>
        Friend Shared ReadOnly Property defaultValue() As String
            Get
                Return ResourceManager.GetString("defaultValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://www.mywebsite.com.
        '''</summary>
        Friend Shared ReadOnly Property defaultWebsite() As String
            Get
                Return ResourceManager.GetString("defaultWebsite", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Window{0}.
        '''</summary>
        Friend Shared ReadOnly Property defaultWindowName() As String
            Get
                Return ResourceManager.GetString("defaultWindowName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fade.
        '''</summary>
        Friend Shared ReadOnly Property effect_Fade() As String
            Get
                Return ResourceManager.GetString("effect_Fade", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fade in only.
        '''</summary>
        Friend Shared ReadOnly Property effect_FadeIn() As String
            Get
                Return ResourceManager.GetString("effect_FadeIn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fade out only.
        '''</summary>
        Friend Shared ReadOnly Property effect_FadeOut() As String
            Get
                Return ResourceManager.GetString("effect_FadeOut", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to None.
        '''</summary>
        Friend Shared ReadOnly Property effect_None() As String
            Get
                Return ResourceManager.GetString("effect_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error occured while {0}  {1}.
        '''</summary>
        Friend Shared ReadOnly Property errLog() As String
            Get
                Return ResourceManager.GetString("errLog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error.
        '''</summary>
        Friend Shared ReadOnly Property error_() As String
            Get
                Return ResourceManager.GetString("error_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Counter doesn&apos;t exist!.
        '''</summary>
        Friend Shared ReadOnly Property error_CounterDoesntExist() As String
            Get
                Return ResourceManager.GetString("error_CounterDoesntExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Device could not be created. Be sure your video card is compatible with DirectX 9..
        '''</summary>
        Friend Shared ReadOnly Property error_DirectX() As String
            Get
                Return ResourceManager.GetString("error_DirectX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot initialize DirectX 9..
        '''</summary>
        Friend Shared ReadOnly Property error_DirectXInit() As String
            Get
                Return ResourceManager.GetString("error_DirectXInit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your video card does not support fullscreen dialog boxes. This program may not run as intended..
        '''</summary>
        Friend Shared ReadOnly Property error_FullscreenDialog() As String
            Get
                Return ResourceManager.GetString("error_FullscreenDialog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ignore &amp;All.
        '''</summary>
        Friend Shared ReadOnly Property error_IgnoreAllButton() As String
            Get
                Return ResourceManager.GetString("error_IgnoreAllButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Ignore.
        '''</summary>
        Friend Shared ReadOnly Property error_IgnoreButton() As String
            Get
                Return ResourceManager.GetString("error_IgnoreButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Initialization failed..
        '''</summary>
        Friend Shared ReadOnly Property error_InitFailed() As String
            Get
                Return ResourceManager.GetString("error_InitFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This is not a valid JumpCraft {0}  Game file.\n\nCannot load file..
        '''</summary>
        Friend Shared ReadOnly Property error_InvalidFile() As String
            Get
                Return ResourceManager.GetString("error_InvalidFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \n\nError message: {0}.
        '''</summary>
        Friend Shared ReadOnly Property error_InvalidFileErrorMessage() As String
            Get
                Return ResourceManager.GetString("error_InvalidFileErrorMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error occured when trying to open the file, &quot;{0}&quot;..
        '''</summary>
        Friend Shared ReadOnly Property error_LoadGame() As String
            Get
                Return ResourceManager.GetString("error_LoadGame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to load the sound, &quot;{0}&quot;.\nError message: {1}.
        '''</summary>
        Friend Shared ReadOnly Property error_LoadSounds() As String
            Get
                Return ResourceManager.GetString("error_LoadSounds", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sound Error.
        '''</summary>
        Friend Shared ReadOnly Property error_LoadSoundsTitle() As String
            Get
                Return ResourceManager.GetString("error_LoadSoundsTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot load tileset.\n\nError message: {0}.
        '''</summary>
        Friend Shared ReadOnly Property error_LoadTileset() As String
            Get
                Return ResourceManager.GetString("error_LoadTileset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Load Tileset.
        '''</summary>
        Friend Shared ReadOnly Property error_LoadTilesetTitle() As String
            Get
                Return ResourceManager.GetString("error_LoadTilesetTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error has occured while.
        '''</summary>
        Friend Shared ReadOnly Property error_Message() As String
            Get
                Return ResourceManager.GetString("error_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This method is not accessible through scripting..
        '''</summary>
        Friend Shared ReadOnly Property error_MethodNotAccessible() As String
            Get
                Return ResourceManager.GetString("error_MethodNotAccessible", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to open the MIDI device..
        '''</summary>
        Friend Shared ReadOnly Property error_MIDIDevice() As String
            Get
                Return ResourceManager.GetString("error_MIDIDevice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There was a problem with the current MIDI file..
        '''</summary>
        Friend Shared ReadOnly Property error_MIDIError() As String
            Get
                Return ResourceManager.GetString("error_MIDIError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File created with a newer version of JumpCraft..
        '''</summary>
        Friend Shared ReadOnly Property error_NewerFile() As String
            Get
                Return ResourceManager.GetString("error_NewerFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This property is not accessible through scripting..
        '''</summary>
        Friend Shared ReadOnly Property error_PropertyNotAccessible() As String
            Get
                Return ResourceManager.GetString("error_PropertyNotAccessible", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Quit.
        '''</summary>
        Friend Shared ReadOnly Property error_QuitButton() As String
            Get
                Return ResourceManager.GetString("error_QuitButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to save to the file, &quot;{0}deftileset.pst&quot;.\n\nError message: {1}.
        '''</summary>
        Friend Shared ReadOnly Property error_SaveDefaultTileset() As String
            Get
                Return ResourceManager.GetString("error_SaveDefaultTileset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error has occured while trying to save the file..
        '''</summary>
        Friend Shared ReadOnly Property error_SaveFile() As String
            Get
                Return ResourceManager.GetString("error_SaveFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error occured when trying to save the file, &quot;{0}&quot;..
        '''</summary>
        Friend Shared ReadOnly Property error_SaveGame() As String
            Get
                Return ResourceManager.GetString("error_SaveGame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save Tileset.
        '''</summary>
        Friend Shared ReadOnly Property error_SaveTilesetError() As String
            Get
                Return ResourceManager.GetString("error_SaveTilesetError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A fatal error has occured. {0} will shut down..
        '''</summary>
        Friend Shared ReadOnly Property fatalError() As String
            Get
                Return ResourceManager.GetString("fatalError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel loading.
        '''</summary>
        Friend Shared ReadOnly Property fileNotFound_CancelLoadingOption() As String
            Get
                Return ResourceManager.GetString("fileNotFound_CancelLoadingOption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to For future errors wihle the current game is loading,.
        '''</summary>
        Friend Shared ReadOnly Property fileNotFound_FutureErrorsFrame() As String
            Get
                Return ResourceManager.GetString("fileNotFound_FutureErrorsFrame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ignore.
        '''</summary>
        Friend Shared ReadOnly Property fileNotFound_IgnoreOption() As String
            Get
                Return ResourceManager.GetString("fileNotFound_IgnoreOption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error occured while trying to find a file to open..
        '''</summary>
        Friend Shared ReadOnly Property fileNotFound_Label() As String
            Get
                Return ResourceManager.GetString("fileNotFound_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The file, &quot;{0}&quot;, could not be found..
        '''</summary>
        Friend Shared ReadOnly Property fileNotFound_Message() As String
            Get
                Return ResourceManager.GetString("fileNotFound_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Replace.
        '''</summary>
        Friend Shared ReadOnly Property fileNotFound_ReplaceOption() As String
            Get
                Return ResourceManager.GetString("fileNotFound_ReplaceOption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Retry.
        '''</summary>
        Friend Shared ReadOnly Property fileNotFound_RetryOption() As String
            Get
                Return ResourceManager.GetString("fileNotFound_RetryOption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show this dialog.
        '''</summary>
        Friend Shared ReadOnly Property fileNotFound_ShowThisDialogOption() As String
            Get
                Return ResourceManager.GetString("fileNotFound_ShowThisDialogOption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Specify a new file.
        '''</summary>
        Friend Shared ReadOnly Property fileNotFound_SpecifyNewFileOption() As String
            Get
                Return ResourceManager.GetString("fileNotFound_SpecifyNewFileOption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File Not Found.
        '''</summary>
        Friend Shared ReadOnly Property fileNotFound_Title() As String
            Get
                Return ResourceManager.GetString("fileNotFound_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to What would you like to do?.
        '''</summary>
        Friend Shared ReadOnly Property fileNotFound_WhatToDoFrame() As String
            Get
                Return ResourceManager.GetString("fileNotFound_WhatToDoFrame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to with.
        '''</summary>
        Friend Shared ReadOnly Property fileNotFound_With() As String
            Get
                Return ResourceManager.GetString("fileNotFound_With", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FPS.
        '''</summary>
        Friend Shared ReadOnly Property fpsUnit() As String
            Get
                Return ResourceManager.GetString("fpsUnit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;End Game.
        '''</summary>
        Friend Shared ReadOnly Property gameEndGameMenu() As String
            Get
                Return ResourceManager.GetString("gameEndGameMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;High Scores.
        '''</summary>
        Friend Shared ReadOnly Property gameHighScoresMenu() As String
            Get
                Return ResourceManager.GetString("gameHighScoresMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Game.
        '''</summary>
        Friend Shared ReadOnly Property gameMenu() As String
            Get
                Return ResourceManager.GetString("gameMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;New Game.
        '''</summary>
        Friend Shared ReadOnly Property gameNewGameMenu() As String
            Get
                Return ResourceManager.GetString("gameNewGameMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Pause.
        '''</summary>
        Friend Shared ReadOnly Property gamePauseMenu() As String
            Get
                Return ResourceManager.GetString("gamePauseMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Quit.
        '''</summary>
        Friend Shared ReadOnly Property gameQuitMenu() As String
            Get
                Return ResourceManager.GetString("gameQuitMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Resume.
        '''</summary>
        Friend Shared ReadOnly Property gameResumeMenu() As String
            Get
                Return ResourceManager.GetString("gameResumeMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JumpCraft Game Tester.
        '''</summary>
        Friend Shared ReadOnly Property gameTesterTitle() As String
            Get
                Return ResourceManager.GetString("gameTesterTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;This code imports the current game object\n&apos;so it can be used through scripting.\n&apos;The Game object is set by the game player..
        '''</summary>
        Friend Shared ReadOnly Property globalsCodeComment() As String
            Get
                Return ResourceManager.GetString("globalsCodeComment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;About.
        '''</summary>
        Friend Shared ReadOnly Property helpAboutMenu() As String
            Get
                Return ResourceManager.GetString("helpAboutMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Help.
        '''</summary>
        Friend Shared ReadOnly Property helpMenu() As String
            Get
                Return ResourceManager.GetString("helpMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show &amp;Help.
        '''</summary>
        Friend Shared ReadOnly Property helpShowHelpMenu() As String
            Get
                Return ResourceManager.GetString("helpShowHelpMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Support.
        '''</summary>
        Friend Shared ReadOnly Property helpSupportMenu() As String
            Get
                Return ResourceManager.GetString("helpSupportMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Website.
        '''</summary>
        Friend Shared ReadOnly Property helpWebsiteMenu() As String
            Get
                Return ResourceManager.GetString("helpWebsiteMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Congratulations, you got a high score!.
        '''</summary>
        Friend Shared ReadOnly Property highScores_Congrats() As String
            Get
                Return ResourceManager.GetString("highScores_Congrats", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter your name..
        '''</summary>
        Friend Shared ReadOnly Property highScores_EnterName() As String
            Get
                Return ResourceManager.GetString("highScores_EnterName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Level.
        '''</summary>
        Friend Shared ReadOnly Property highScores_Level() As String
            Get
                Return ResourceManager.GetString("highScores_Level", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name.
        '''</summary>
        Friend Shared ReadOnly Property highScores_Name() As String
            Get
                Return ResourceManager.GetString("highScores_Name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rank.
        '''</summary>
        Friend Shared ReadOnly Property highScores_Rank() As String
            Get
                Return ResourceManager.GetString("highScores_Rank", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Score.
        '''</summary>
        Friend Shared ReadOnly Property highScores_Score() As String
            Get
                Return ResourceManager.GetString("highScores_Score", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to High Score!.
        '''</summary>
        Friend Shared ReadOnly Property highScores_Title() As String
            Get
                Return ResourceManager.GetString("highScores_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Import Tileset.
        '''</summary>
        Friend Shared ReadOnly Property importTileset() As String
            Get
                Return ResourceManager.GetString("importTileset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Advanced.
        '''</summary>
        Friend Shared ReadOnly Property importTileset_AdvancedFrame() As String
            Get
                Return ResourceManager.GetString("importTileset_AdvancedFrame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Import and replace counter actions.
        '''</summary>
        Friend Shared ReadOnly Property importTileset_ImportCounterActionsCheckbox() As String
            Get
                Return ResourceManager.GetString("importTileset_ImportCounterActionsCheckbox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Import and replace general actions.
        '''</summary>
        Friend Shared ReadOnly Property importTileset_ImportGeneralActionsCheckbox() As String
            Get
                Return ResourceManager.GetString("importTileset_ImportGeneralActionsCheckbox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Import and replace group actions.
        '''</summary>
        Friend Shared ReadOnly Property importTileset_ImportGroupActionsCheckbox() As String
            Get
                Return ResourceManager.GetString("importTileset_ImportGroupActionsCheckbox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Import and replace other actions.
        '''</summary>
        Friend Shared ReadOnly Property importTileset_ImportOtherActionsCheckbox() As String
            Get
                Return ResourceManager.GetString("importTileset_ImportOtherActionsCheckbox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Import and replace timer actions.
        '''</summary>
        Friend Shared ReadOnly Property importTileset_ImportTimerActionsCheckbox() As String
            Get
                Return ResourceManager.GetString("importTileset_ImportTimerActionsCheckbox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select tiles to import (use Shift and Ctrl to select multiple tiles):.
        '''</summary>
        Friend Shared ReadOnly Property importTileset_Instructions() As String
            Get
                Return ResourceManager.GetString("importTileset_Instructions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Replace tiles with same name.
        '''</summary>
        Friend Shared ReadOnly Property importTileset_ReplaceTilesCheckbox() As String
            Get
                Return ResourceManager.GetString("importTileset_ReplaceTilesCheckbox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Import Tileset.
        '''</summary>
        Friend Shared ReadOnly Property importTileset_Title() As String
            Get
                Return ResourceManager.GetString("importTileset_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid data file, &quot;data2.dat&quot;..
        '''</summary>
        Friend Shared ReadOnly Property invalidData2File() As String
            Get
                Return ResourceManager.GetString("invalidData2File", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Level Error.
        '''</summary>
        Friend Shared ReadOnly Property levelError() As String
            Get
                Return ResourceManager.GetString("levelError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No character tile exists in the Background, Foreground, or Front layers of level, &quot;{0}&quot;.\n\nIf this error is ignored, the character tile will be set to (1, 1) of the Foreground layer..
        '''</summary>
        Friend Shared ReadOnly Property levelErrorNoCharacter() As String
            Get
                Return ResourceManager.GetString("levelErrorNoCharacter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to loading a level.
        '''</summary>
        Friend Shared ReadOnly Property levelErrorOccurredWhileLoadingLevel() As String
            Get
                Return ResourceManager.GetString("levelErrorOccurredWhileLoadingLevel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading tileset....
        '''</summary>
        Friend Shared ReadOnly Property loadingTilesetStatus() As String
            Get
                Return ResourceManager.GetString("loadingTilesetStatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The tile, &quot;{0}&quot; has a name that conflicts with an existing tile.Import anyway?\n\nNote: The tile will be imported as &quot;{1}&quot;..
        '''</summary>
        Friend Shared ReadOnly Property loadTileConflict() As String
            Get
                Return ResourceManager.GetString("loadTileConflict", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JumpCraft is looking for the file, &quot;{0}&quot;. This process might take awhile. Would you like to continue?.
        '''</summary>
        Friend Shared ReadOnly Property lookingForFileMessage() As String
            Get
                Return ResourceManager.GetString("lookingForFileMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (none).
        '''</summary>
        Friend Shared ReadOnly Property noValue() As String
            Get
                Return ResourceManager.GetString("noValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;OK.
        '''</summary>
        Friend Shared ReadOnly Property okButton() As String
            Get
                Return ResourceManager.GetString("okButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select a File.
        '''</summary>
        Friend Shared ReadOnly Property selectAFileDialogTitle() As String
            Get
                Return ResourceManager.GetString("selectAFileDialogTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tileset Error.
        '''</summary>
        Friend Shared ReadOnly Property tilesetError() As String
            Get
                Return ResourceManager.GetString("tilesetError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No character tile exists. Make sure a tile in the tileset has a behavior marked, &quot;Character&quot;.\n\nIf this error is ignored, the character tile will be set to the first tile of the tileset)..
        '''</summary>
        Friend Shared ReadOnly Property tilesetErrorNoCharacter() As String
            Get
                Return ResourceManager.GetString("tilesetErrorNoCharacter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No tiles exist in the tileset. Make sure there is at least one tile in the tileset, and one tile exists whose behavior is marked as &quot;Character&quot;..
        '''</summary>
        Friend Shared ReadOnly Property tilesetErrorNoTiles() As String
            Get
                Return ResourceManager.GetString("tilesetErrorNoTiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to finding the char. tile.
        '''</summary>
        Friend Shared ReadOnly Property tilesetErrorOccuredWhileFindingCharacterTile() As String
            Get
                Return ResourceManager.GetString("tilesetErrorOccuredWhileFindingCharacterTile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to loading the game.
        '''</summary>
        Friend Shared ReadOnly Property tilesetErrorOccurredWhileLoadingGame() As String
            Get
                Return ResourceManager.GetString("tilesetErrorOccurredWhileLoadingGame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File cannot be opened..
        '''</summary>
        Friend Shared ReadOnly Property updateFileFailedMessage() As String
            Get
                Return ResourceManager.GetString("updateFileFailedMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This file was created in a previous version of JumpCraft. Update file?\n\nWARNING: Files saved in newer versions of JumpCraft cannot be opened in older versions..
        '''</summary>
        Friend Shared ReadOnly Property updateFileMessage() As String
            Get
                Return ResourceManager.GetString("updateFileMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Upgrade warning:\n{0}.
        '''</summary>
        Friend Shared ReadOnly Property upgradeWarning() As String
            Get
                Return ResourceManager.GetString("upgradeWarning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AboutButton.
        '''</summary>
        Friend Shared ReadOnly Property windows_AboutButton() As String
            Get
                Return ResourceManager.GetString("windows_AboutButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to About.
        '''</summary>
        Friend Shared ReadOnly Property windows_AboutButtonText() As String
            Get
                Return ResourceManager.GetString("windows_AboutButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} Version {1}\n\n{2}\n\nCopyright {3}, {4}.
        '''</summary>
        Friend Shared ReadOnly Property windows_AboutDialogMessage() As String
            Get
                Return ResourceManager.GetString("windows_AboutDialogMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to About {0}.
        '''</summary>
        Friend Shared ReadOnly Property windows_AboutDialogTitle() As String
            Get
                Return ResourceManager.GetString("windows_AboutDialogTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AboutLabel.
        '''</summary>
        Friend Shared ReadOnly Property windows_AboutLabel() As String
            Get
                Return ResourceManager.GetString("windows_AboutLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to About {0}.
        '''</summary>
        Friend Shared ReadOnly Property windows_AboutLabelText() As String
            Get
                Return ResourceManager.GetString("windows_AboutLabelText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AboutOKButton.
        '''</summary>
        Friend Shared ReadOnly Property windows_AboutOKButton() As String
            Get
                Return ResourceManager.GetString("windows_AboutOKButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Friend Shared ReadOnly Property windows_AboutOKButtonText() As String
            Get
                Return ResourceManager.GetString("windows_AboutOKButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AboutText.
        '''</summary>
        Friend Shared ReadOnly Property windows_AboutText() As String
            Get
                Return ResourceManager.GetString("windows_AboutText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to About.
        '''</summary>
        Friend Shared ReadOnly Property windows_AboutWindow() As String
            Get
                Return ResourceManager.GetString("windows_AboutWindow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ExitButton.
        '''</summary>
        Friend Shared ReadOnly Property windows_ExitButton() As String
            Get
                Return ResourceManager.GetString("windows_ExitButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exit.
        '''</summary>
        Friend Shared ReadOnly Property windows_ExitButtonText() As String
            Get
                Return ResourceManager.GetString("windows_ExitButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GameArea.
        '''</summary>
        Friend Shared ReadOnly Property windows_GameArea() As String
            Get
                Return ResourceManager.GetString("windows_GameArea", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game Area.
        '''</summary>
        Friend Shared ReadOnly Property windows_GameAreaPlaceholder() As String
            Get
                Return ResourceManager.GetString("windows_GameAreaPlaceholder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game.
        '''</summary>
        Friend Shared ReadOnly Property windows_GameWindow() As String
            Get
                Return ResourceManager.GetString("windows_GameWindow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to HealthCounter.
        '''</summary>
        Friend Shared ReadOnly Property windows_HealthCounter() As String
            Get
                Return ResourceManager.GetString("windows_HealthCounter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to HelpButton.
        '''</summary>
        Friend Shared ReadOnly Property windows_HelpButton() As String
            Get
                Return ResourceManager.GetString("windows_HelpButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Help.
        '''</summary>
        Friend Shared ReadOnly Property windows_HelpButtonText() As String
            Get
                Return ResourceManager.GetString("windows_HelpButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to HelpLabel.
        '''</summary>
        Friend Shared ReadOnly Property windows_HelpLabel() As String
            Get
                Return ResourceManager.GetString("windows_HelpLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Help.
        '''</summary>
        Friend Shared ReadOnly Property windows_HelpLabelText() As String
            Get
                Return ResourceManager.GetString("windows_HelpLabelText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to HelpOKButton.
        '''</summary>
        Friend Shared ReadOnly Property windows_HelpOKButton() As String
            Get
                Return ResourceManager.GetString("windows_HelpOKButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Friend Shared ReadOnly Property windows_HelpOKButtonText() As String
            Get
                Return ResourceManager.GetString("windows_HelpOKButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to HelpText.
        '''</summary>
        Friend Shared ReadOnly Property windows_HelpText() As String
            Get
                Return ResourceManager.GetString("windows_HelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Help.
        '''</summary>
        Friend Shared ReadOnly Property windows_HelpWindow() As String
            Get
                Return ResourceManager.GetString("windows_HelpWindow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to High Scores Area.
        '''</summary>
        Friend Shared ReadOnly Property windows_HighScoresPlaceholder() As String
            Get
                Return ResourceManager.GetString("windows_HighScoresPlaceholder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to High Scores.
        '''</summary>
        Friend Shared ReadOnly Property windows_HighScoresWindow() As String
            Get
                Return ResourceManager.GetString("windows_HighScoresWindow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (Image Counter).
        '''</summary>
        Friend Shared ReadOnly Property windows_ImageCounterPlaceholder() As String
            Get
                Return ResourceManager.GetString("windows_ImageCounterPlaceholder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LevelCompleteLabel.
        '''</summary>
        Friend Shared ReadOnly Property windows_LevelCompletedLabel() As String
            Get
                Return ResourceManager.GetString("windows_LevelCompletedLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Level Complete!\nPrepare for {0}.
        '''</summary>
        Friend Shared ReadOnly Property windows_LevelCompletedLabelText() As String
            Get
                Return ResourceManager.GetString("windows_LevelCompletedLabelText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Level Completed.
        '''</summary>
        Friend Shared ReadOnly Property windows_LevelCompletedWindow() As String
            Get
                Return ResourceManager.GetString("windows_LevelCompletedWindow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} Completed.
        '''</summary>
        Friend Shared ReadOnly Property windows_LevelXCompletedWindow() As String
            Get
                Return ResourceManager.GetString("windows_LevelXCompletedWindow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LivesCounter.
        '''</summary>
        Friend Shared ReadOnly Property windows_LivesCounter() As String
            Get
                Return ResourceManager.GetString("windows_LivesCounter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LoseLabel.
        '''</summary>
        Friend Shared ReadOnly Property windows_LoseLabel() As String
            Get
                Return ResourceManager.GetString("windows_LoseLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sorry, You Lose!.
        '''</summary>
        Friend Shared ReadOnly Property windows_LoseLabelText() As String
            Get
                Return ResourceManager.GetString("windows_LoseLabelText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LoseOKButton.
        '''</summary>
        Friend Shared ReadOnly Property windows_LoseOKButton() As String
            Get
                Return ResourceManager.GetString("windows_LoseOKButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Friend Shared ReadOnly Property windows_LoseOKButtonText() As String
            Get
                Return ResourceManager.GetString("windows_LoseOKButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lose.
        '''</summary>
        Friend Shared ReadOnly Property windows_LoseWindow() As String
            Get
                Return ResourceManager.GetString("windows_LoseWindow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Main.
        '''</summary>
        Friend Shared ReadOnly Property windows_Main() As String
            Get
                Return ResourceManager.GetString("windows_Main", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MainLabel.
        '''</summary>
        Friend Shared ReadOnly Property windows_MainLabel() As String
            Get
                Return ResourceManager.GetString("windows_MainLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Movie.
        '''</summary>
        Friend Shared ReadOnly Property windows_MoviePlaceholder() As String
            Get
                Return ResourceManager.GetString("windows_MoviePlaceholder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PauseButton.
        '''</summary>
        Friend Shared ReadOnly Property windows_PauseButton() As String
            Get
                Return ResourceManager.GetString("windows_PauseButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pause.
        '''</summary>
        Friend Shared ReadOnly Property windows_PauseButtonText() As String
            Get
                Return ResourceManager.GetString("windows_PauseButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PauseLabel.
        '''</summary>
        Friend Shared ReadOnly Property windows_PauseLabel() As String
            Get
                Return ResourceManager.GetString("windows_PauseLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game Paused.\nClick &quot;Resume&quot; to continue..
        '''</summary>
        Friend Shared ReadOnly Property windows_PauseText() As String
            Get
                Return ResourceManager.GetString("windows_PauseText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pause.
        '''</summary>
        Friend Shared ReadOnly Property windows_PauseWindow() As String
            Get
                Return ResourceManager.GetString("windows_PauseWindow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PlayButton.
        '''</summary>
        Friend Shared ReadOnly Property windows_PlayButton() As String
            Get
                Return ResourceManager.GetString("windows_PlayButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Play.
        '''</summary>
        Friend Shared ReadOnly Property windows_PlayButtonText() As String
            Get
                Return ResourceManager.GetString("windows_PlayButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to QuitButton.
        '''</summary>
        Friend Shared ReadOnly Property windows_QuitButton() As String
            Get
                Return ResourceManager.GetString("windows_QuitButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Quit.
        '''</summary>
        Friend Shared ReadOnly Property windows_QuitButtonText() As String
            Get
                Return ResourceManager.GetString("windows_QuitButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ResumeButton.
        '''</summary>
        Friend Shared ReadOnly Property windows_ResumeButton() As String
            Get
                Return ResourceManager.GetString("windows_ResumeButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resume.
        '''</summary>
        Friend Shared ReadOnly Property windows_ResumeText() As String
            Get
                Return ResourceManager.GetString("windows_ResumeText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ScoreCounter.
        '''</summary>
        Friend Shared ReadOnly Property windows_ScoreCounter() As String
            Get
                Return ResourceManager.GetString("windows_ScoreCounter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SupportButton.
        '''</summary>
        Friend Shared ReadOnly Property windows_SupportButton() As String
            Get
                Return ResourceManager.GetString("windows_SupportButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Support.
        '''</summary>
        Friend Shared ReadOnly Property windows_SupportButtonText() As String
            Get
                Return ResourceManager.GetString("windows_SupportButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WebsiteButton.
        '''</summary>
        Friend Shared ReadOnly Property windows_WebsiteButton() As String
            Get
                Return ResourceManager.GetString("windows_WebsiteButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Website.
        '''</summary>
        Friend Shared ReadOnly Property windows_WebsiteButtonText() As String
            Get
                Return ResourceManager.GetString("windows_WebsiteButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WinLabel.
        '''</summary>
        Friend Shared ReadOnly Property windows_WinLabel() As String
            Get
                Return ResourceManager.GetString("windows_WinLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Congratulations, You Win!.
        '''</summary>
        Friend Shared ReadOnly Property windows_WinLabelText() As String
            Get
                Return ResourceManager.GetString("windows_WinLabelText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WinOKButton.
        '''</summary>
        Friend Shared ReadOnly Property windows_WinOKButton() As String
            Get
                Return ResourceManager.GetString("windows_WinOKButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Friend Shared ReadOnly Property windows_WinOKButtonText() As String
            Get
                Return ResourceManager.GetString("windows_WinOKButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Win.
        '''</summary>
        Friend Shared ReadOnly Property windows_WinWindow() As String
            Get
                Return ResourceManager.GetString("windows_WinWindow", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
